### PR TITLE
Fixes for CUDNN 8.4.1

### PR DESCRIPTION
**Pull request by corepointer**

### CODE REVIEW

**Comment by jcuda** [comment]
I had a short look at the code and changes, and am somewhat confused: For me, the "wrong" version compiles without issues. 

I'll have a closer look at this ASAP (likely in the next few days). The function signatures are part of the auto-generated code (so the actual fix would be in the code generator), so I will not _merge_ this PR, but only close it when I have done the respective fixes locally. (EDITED: I'll have to review what the actual function signatures are supposed to be - i.e. whether this is host- or device memory. I think it is device memory, so it should be a `jobject` and no `jintArray`, but I might be mistaken)

**Comment by corepointer** [comment]
* Maybe the cudnn function handles the host to device transfer itself? I did not test the functionality tbh.
* When fixing this, I already thought that it'd be of minor value because you need to fix the code generator anyway. But I wanted to see if it compiles if I fix those few function calls :D 
* Sorry to have confused you. It is of course not a compilation issue but a runtime issue while running the tests invoked by mvn install.

**Comment by jcuda** [comment]
> But I wanted to see if it compiles if I fix those few function calls :D

👍 for that. I can only try to increase the test coverage by porting samples and see whether they "work". Each program that really _uses_ a function (beyond the 'basic binding test') can be helpful here. 


> Maybe the cudnn function handles the host to device transfer itself? 

Usually not. CUDA tends to be lazy and inconvenient in that regard. The code generator can generate bindings for an `int*` that can, for example, be a Java `int[]` or a `Pointer` (and for the latter, there's the difference between host- and device pointers), and it's not always clear what the "right" solution is.

But as mentioned above: I think that in the last version, there is a fundamental incompatibility between (core) CUDA and cuDNN, and this causes crashes (terminating the VM). I'll have to investigate that further as soon as I can allocate the time...

**Comment by jcuda** [comment]
I had a closer look at this (with some delay now...)

From what I see, the change largely consists for changing former `Pointer` arguments into `int[]` arrays. For example, in [`cudnnMultiHeadAttnForward`](https://github.com/jcuda/jcudnn/pull/6/files#diff-e33271ed4253850c84425f3d87a51d9e93fb1c56197df4a4e5c303c3ba8657b1R8206) for the `devSeqLengthsQO` and `devSeqLengthsKV` parameters.

But looking at the [documentation of `cudnnMultiHeadAttnForward` ](https://docs.nvidia.com/deeplearning/cudnn/api/index.html#cudnnMultiHeadAttnForward), these are documented as

> devSeqLengthsQO[]
> Input. Device array specifying sequence lengths of query, residual, and output sequence data.
> devSeqLengthsKV[]
> Input. Device array specifying sequence lengths of key and value input data.

so they should be _device_ arrays (represented as a `Pointer`)

I did not check the documentation of each of them, but their names all start with `dev...`, so I assume that they indeed _are_ alll device pointers.

**Comment by jcuda** [comment]
From my understanding, and after some hassle (details at https://github.com/jcuda/jcuda-main/issues/50#issuecomment-1179543708 ), this should be obsolete. If the same problem appears again, feel free to reopen this.

**Pull request closed without merging**
